### ISSUE TITLE
RFC: Additional types and directory structure

### ISSUE THREAD

**Issue by sandersch** [elanthia-online/jinx#36]
I would like to add support for all the asset types required to fully update (and eventually install from script) a lich installation. Currently, we support:

* script
* data

and I am proposing that we also support:

* map (image files)
* engine (e.g. lich.rb)

Are there additional types needed that I am overlooking?

As part of adding these new types of files, I would also like to propose that we organize them into directories by type. I updated `jinxp` to detect the new types based on file name/extension, but I think it would be easier for humans find things in this repo and also better support different workflows for different types of assets if we split them into different directories.

**Comment by ondreian** [comment]
Seems reasonable, though I think some assets like mapdb/spell-list.xml/etc will need pre-processing steps anyway that keep them outside of `lib/`

**Comment by mrhoribu** [comment]
I'm in agreement. It would make sense to have it mirror the naming possibly of how it's installed for a Lich/Urnon install though. So scripts would be in scripts and data would be in data.

**Comment by sandersch** [comment]
Added support for engine and map types in https://github.com/elanthia-online/jinxp/pull/6 and just merged #37 to add the lich.rb engine to this repo. Didn't create separate folders yet but probably going to tackle getting map images added soon which will make it necessary.
